# Generated by Django 5.1.1 on 2024-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='feedback_status',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='solution_details',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
