# Generated by Django 5.1.1 on 2024-09-25 10:10

import App_Survey.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0002_complain_feedback_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='student_id',
            field=models.CharField(max_length=8, validators=[App_Survey.models.validate_student_id]),
        ),
    ]
