# Generated by Django 5.1.1 on 2024-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0006_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='feedback_status',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
    ]
