# Generated by Django 5.1.1 on 2024-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0011_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='shutdown_end_time',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shutdown_start_time',
            field=models.TimeField(default='21:00'),
        ),
    ]
