# Generated by Django 5.1.1 on 2024-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Survey', '0012_sitesettings_shutdown_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='shutdown_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shutdown_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
